baseURL = "https://mzegar.github.io/"
languageCode = "en-us"
theme = "reloaded"
title = "Matthew Zegar | Personal Website"

[menu]
    [[menu.main]]
        name = "Posts"
        pre = "pen-tool"
        url = "/posts/"
        weight = 2
    [[menu.main]]
        name = "Tags"
        pre = "tag"
        url = "/tags/"
        weight = 3
